### ISSUE TITLE
Split multicorecheck.opam into two separate opam packages

### ISSUE THREAD

**Issue by jmid** [jmid/multicoretests#119]
The `multicorecheck` opam package is a bit artificial as it is unclear to new-comers how it relates to the two libraries.
It has nevertheless worked well to get this effort going.

Before publishing on the `opam` repo, I suggest we split the `multicorecheck` opam package in two
- a `Lin` package
- a `qcheck-stm` package

I propose the latter name to help pick up opam package search queries, as `STM` is a missing "add-on" functionality of `QCheck`.

**Comment by OlivierNicole** [comment]
The new names seem sensible to me.
