### ISSUE TITLE
Omit gh-pages from compiler testing workflows

### ISSUE THREAD

**Issue by jmid** [jmid/multicoretests#173]
The workflow in #172 builds documentation and pushes it to the `gh-pages` branch.

However, the `common.yml` workflows fail when the CI try to run them on the code-free `gh-pages` branch:
https://github.com/jmid/multicoretests/actions/runs/3394723547

@shym Can you help to work-in a `branches-ignore: gh-pages` into the existing compiler testing workflows?
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-branches-and-tags

**Comment by shym** [comment]
Is #174 what you were looking for? Or I missed something.

**Comment by jmid** [comment]
Ha! Very nice - while removing the source code from the `gh-pages` I clearly missed the hidden `.github`-directory :sweat_smile: 
Thanks! :pray:

**Comment by jmid** [comment]
Fixed by #174
