### ISSUE TITLE
Remove AddGc functor in STM

### ISSUE THREAD

**Issue by jmid** [jmid/multicoretests#178]
For the forthcoming initial release we should consider removing the `AddGc` functor from STM.
It was an early experiment to see whether having explicit GC calls interleaved would increase the chance of triggering issues. 
However it doesn't seem to be the case, nor is the `AddGc` feature used in any of our own STM tests.

We should probably keep the feature on a separate branch in case it will be needed later...

**Comment by n-osborne** [comment]
I agree that we should not release unnecessary features.
I won't include `AddGc` in the documentation I'm writing then.
