### ISSUE TITLE
Cancel a PR's earlier CI jobs on subsequent pushes

### ISSUE THREAD

**Issue by jmid** [jmid/multicoretests#225]
We sometimes find ourselves in a situation where
- you open a PR, kicking off a long CI-run
- you spot an oversight in your PR and push a commit fix, thereby launching a second, long CI-run

On the fix-push it would be nice to automatically cancel the earlier CI jobs.
(for context, I saw a recent PR on ocaml/ocaml providing this)

**Comment by shym** [comment]
I usually cancel workflows by hand when this happens. But indeed, contributors cannot cancel runs due to a PR on the main repo, so this would be good!
