### ISSUE TITLE
Unnecessary calls to cpu_relax when sequentially executing commands

### ISSUE THREAD

**Issue by OlivierNicole** [jmid/multicoretests#43]
Currently, when searching for an interleaving matching observations, `Lin` will call `Domain.cpu_relax ()` for every command run: https://github.com/jmid/multicoretests/blob/8a9a2327e06036f06ca5ef4b1321129ccff557d6/lib/lin.ml#L42-L45
even when running commands sequentially.

I realized this because a very quick `perf top` during lin tests of `Array.{get,set}` showed that the function using the biggest share of cycles was `cpu_relax`. This suggests that we should not call it, at least in sequential mode, as it has an intrinsic cost.

I did a quick attempt to remove the call to `cpu_relax` in the above `interp` function. This seems to speed up the Array lin test below—although I didn't take the time to crunch numbers—and trigger inconsistencies considerably more often: I now get a failure after running a few dozen tests, whereas before the change I would get less than one in a thousand tests failing.

*Edit:* The Array lin test in question:
```ocaml
module Array_spec = struct
  type t = int array

  let length = 8

  type cmd = Get of int | Set of int * int
  [@@deriving show { with_path = false }]

  let gen_cmd =
    let get i = Get i in
    let set i v = Set (i,v) in
    let open QCheck.Gen in
    let index = int_bound (length-1) in
    frequency
      [ 1, set <$> index <*> int;
        2, get <$> index;
      ]

  type res = RGet of int | RSet
  [@@deriving show { with_path = false }, eq]

  let init () = Array.make length 42

  let cleanup _ = ()

  let run cmd arr =
    match cmd with
    | Get i -> RGet arr.(i)
    | Set (i,v) -> arr.(i) <- v; RSet
end

module Lin_array = Lin.Make (Array_spec)

let () =
  QCheck_runner.run_tests_main
    [ Lin_array.lin_test       ~count:1000 ~name:"Array"       `Domain;
    ]
```

**Comment by jmid** [comment]
Thanks for taking a look at this! I was also seeing `cpu_relax` at the `perf top`, when I was trying to understand what was happening when the tests would stall for seconds/minutes without progress.

Initially I put `cpu_relax` in `interp` to "maximize for concurrency problems" 
- intending to get back to representing, randomizing, and shrinking such calls akin to the `Yields` in the `Effect` interpretation https://github.com/jmid/multicoretests/blob/8a9a2327e06036f06ca5ef4b1321129ccff557d6/lib/lin.ml#L207-L210 (this could be improved to insert at most one in between each regular `cmd`)
- this was when I was still programming this blind-folded. It would be nice to confirm with statistical significance that `cpu_relax` between each parallel `cmd` actually makes a difference in terms of triggering more problems

I agree that `cpu_relax` during sequential execution is a waste. This happens both during 
- the interleaving search https://github.com/jmid/multicoretests/blob/8a9a2327e06036f06ca5ef4b1321129ccff557d6/lib/lin.ml#L112 
- and while interpreting the sequential prefix https://github.com/jmid/multicoretests/blob/8a9a2327e06036f06ca5ef4b1321129ccff557d6/lib/lin.ml#L121
Using a simpler `interp_seq` here should be a definite win. Such a function could even save the array conversion and allocation thus putting less stress on the GC.


There's one remaining usage of `cpu_relax` in spinning the first domain while waiting for the second domain to start-up:
https://github.com/jmid/multicoretests/blob/8a9a2327e06036f06ca5ef4b1321129ccff557d6/lib/lin.ml#L122-L124
Now that we have statistics in place, it would be natural to give this `Domain` setup a run-down to see what aspects actually influence the bug-finding ability similar to what I did for `Thread` recently: https://github.com/jmid/multicoretests/blob/8a9a2327e06036f06ca5ef4b1321129ccff557d6/src/statistics/README.md?plain=1#L129-L143

For `Thread` a wait loop had an significant effect. For `Domain` it would be nice to confirm - and also investigate whether there could be better ways to accomplish this. In the tests for the work-stealing deque that has now been pulled out of `domainslib` the spinning did not work at all to trigger issues on MacOSX, so I ended up going with a binary semaphore: https://github.com/jmid/multicoretests/blob/8a9a2327e06036f06ca5ef4b1321129ccff557d6/src/domainslib/ws_deque_test.ml#L131-L133
The simpler, the better. A combination of a `Mutex` and a `Condition` variable may also be sufficient.

**Comment by jmid** [comment]
The easiest part of the above is taken care of by #45.
I've also created separate issues #46 and #47 to track the mentioned aspects separately.
