### ISSUE TITLE
Port previous Lin tests to the new signature DSL

### ISSUE THREAD

**Issue by jmid** [jmid/multicoretests#54]
We should port the existing Lin tests to the new signature DSL from #44.
I expect that it will help identify a few missing `GenDeconstr` bindings and thus help make the DSL more feature complete.

There's an initial example in https://github.com/jmid/multicoretests/blob/main/test/lin_api.ml which corresponds to the first half of https://github.com/jmid/multicoretests/blob/main/src/atomic/lin_tests.ml modulo a `nat` generator.

**Comment by OlivierNicole** [comment]
It will be interesting to see if the race conditions are triggered as robustly as without the DSL.

**Comment by jmid** [comment]
Indeed - the right thing will probably be to run statistical tests to compare them 😀

Note: I found and fixed one cause of long interleaving times in #55 - because of too long `cmd list`s.
Cutting down the `list` length however reduced the chance of triggering issues...
As part of the fix I therefore changed strategy to generate two parallel `cmd list`s of equal length.
This increased the chance of finding issues again (with statistical significance).
The DSL-based tests will also benefit from this new generation strategy...

**Comment by n-osborne** [comment]
So I've compared the number of buggy programs found by the original setting and with the DSL on the Hashtbl module. The behaviour is similar. So I guess we can go ahead in porting the tests to the DSL. Except of course if you think of something else to measure.

```bash
$ dune exec -- src/hashtbl/stats.exe
random seed: 112049285
================================================================================
success (ran 2 tests)
Buggy programs with original lin:  978 / 10_000
Buggy programs with dsl:           973 / 10_000

$ dune exec -- src/statistics/z_test.exe 10000 978 10000 973
z-test of two proportions
z = 0.119160
Is |z| = |0.119160| > z_alpha2 = 1.960000 ?
No, failed to reject null hypothesis
```

**Comment by jmid** [comment]
That's great, thanks for checking! :pray: 

I have a work-in-progress translation of some more of the existing tests.
Some of them involve function generation, etc., so I've had to extend the DSL combinator interface slightly...
I can share a WIP-PR so we avoid repeating the work.

**Comment by jmid** [comment]
> I was just looking at how to add function generation, so I'm curious on how you did it.

I have just worked around it - so its not a full solution of #57 - but it is a start :man_shrugging:
